[package]
name = "fermy-todo"
authors = ["Vincenzo Marcella <me@vincenzomarcella.com>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
spin-sdk = "2.2.0"

[workspace]
