spin_manifest_version = 2

[application]
name = "fermy-todo"
version = "0.1.0"
authors = ["Vincenzo Marcella <me@vincenzomarcella.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "fermy-todo"

[component.fermy-todo]
source = "target/wasm32-wasi/release/fermy_todo.wasm"
allowed_outbound_hosts = []
[component.fermy-todo.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
